export const JobListingData = [
  {
    id: 1,
    date: "20/04/2024",
    company: "Amazon",
    title: "Senior UI/UX Designer",
    role1: "Part time",
    role2: "Senior level",
    salary: "$120/hr",
    location: "Switzerland",
  },
  {
    id: 2,
    date: "15/05/2024",
    company: "Google",
    title: "Frontend Developer",
    role1: "Full time",
    role2: "Mid level",
    salary: "$100/hr",
    location: "UK",
  },
  {
    id: 3,
    date: "01/06/2024",
    company: "Facebook",
    title: "Product Manager",
    role1: "Contract",
    role2: "Senior level",
    salary: "$150/hr",
    location: "France",
  },
  {
    id: 4,
    date: "10/07/2024",
    company: "Microsoft",
    title: "Software Engineer",
    role1: "Internship",
    role2: "Entry level",
    salary: "$80/hr",
    location: "Nigeria",
  },
];
